trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: false
bracketSpacing: true
plugins:
  - "prettier-plugin-tailwindcss" # should be last https://github.com/tailwindlabs/prettier-plugin-tailwindcss?tab=readme-ov-file#compatibility-with-other-prettier-plugins
tailwindStylesheet: "./src/index.css"