name: "dashboard"
version: "2.1.1"
usage: "A simplified way of working with Helm"
description: "GUI dashboard for inspecting Helm releases, manifests, revision diffs, and Kubernetes resources"
command: "$HELM_PLUGIN_DIR/bin/helm-dashboard"
ignoreFlags: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
